### ISSUE TITLE
建议去掉对Laravel的Require来支持更多框架。

### ISSUE THREAD

**Issue by Abel94** [ISCLOUDX/alisms#1]
看了一下写法，实际上Lumen也是能够使用此模块的，但是由于`"require": {
    "php": ">=5.5.0",
    "laravel/framework": "5.*"
  },`中的"laravel/framework": "5.*"，composer就加载了整个laravel框架，但这样会和lumen起冲突。

而且这个模块本身没有用到laravel的一些东西，因此require laravel也是不合理的。

**Comment by ISCLOUDX** [comment]
好的 谢谢
