### ISSUE TITLE
smsFreeSignName

### ISSUE THREAD

**Issue by weiloon1234** [ISCLOUDX/alisms#3]
**FatalErrorException in RequestCheckUtil.php line 18:**
**Class 'iscms\AlismsSdk\Exception' not found**

我在文件内将 **throw new Exception** 改为 **throw new \Exception** 问题就解决了，不过出现以下问题

**Exception in RequestCheckUtil.php line 18:**
**client-check-error:Missing Required Arguments: smsFreeSignName**

**Comment by chao** [comment]
提交了一个PR，请早日修复吧。

**Comment by ISCLOUDX** [comment]
不应该出现这个问题啊 我刚使用了 laravel5.2进行测试的 没有任何问题呀

**Comment by chao** [comment]
我也用的5.2，在短信发送异常的时候会报错。你可以这样试一下，你在阿里大鱼里建一个新模版，模版未通过审核。这时候如果抛出异常就会报错。

从代码来看确实是在<code>iscms\AlismsSdk</code>这个namespace 下了，所以加个<code>\\</code>确保调用的是Global的Exception。

**Comment by chao** [comment]
@weiloon1234 你的问题应该是未加签名参数造成的。

**Comment by ISCLOUDX** [comment]
我刚试了一下 模板处于[审批中],[未通过]的时候,返回的是
```
{#163 ▼
  +"code": 15
  +"msg": "Remote service error"
  +"sub_code": "isv.SMS_TEMPLATE_ILLEGAL"
  +"sub_msg": "短信模板不合法"
  +"request_id": "ztafvg7161l4"
}
```

**Comment by ISCLOUDX** [comment]
@chao 
我刚试了一下 模板处于[审批中],[未通过]的时候,返回的是
```
{#163 ▼
  +"code": 15
  +"msg": "Remote service error"
  +"sub_code": "isv.SMS_TEMPLATE_ILLEGAL"
  +"sub_msg": "短信模板不合法"
  +"request_id": "ztafvg7161l4"
}
```

**Comment by chao** [comment]
那就奇怪了。难道是因为我用的是PHP7的原因？我试试PHP5.6的环境吧。
